/* IS_AUTOGENERATED_SO_ALLOW_AUTODELETE=YES */
/* The previous line is to allow auto deletion */

#import <Foundation/Foundation.h>
#import <Foundation/NSString.h>
#import "libGolgi.h"



@interface AccessRequest : NSObject
{
    NSString *uname;
    BOOL unameIsSet;
    NSString *key;
    BOOL keyIsSet;
    NSString *lat;
    BOOL latIsSet;
    NSString *lon;
    BOOL lonIsSet;
    NSString *auth;
    BOOL authIsSet;
    NSInteger tsh;
    BOOL tshIsSet;
    NSInteger tsl;
    BOOL tslIsSet;
}

@property (readonly) BOOL unameIsSet;
- (NSString *)getUname;
- (void)setUname:(NSString *)uname;
@property (readonly) BOOL keyIsSet;
- (NSString *)getKey;
- (void)setKey:(NSString *)key;
@property (readonly) BOOL latIsSet;
- (NSString *)getLat;
- (void)setLat:(NSString *)lat;
@property (readonly) BOOL lonIsSet;
- (NSString *)getLon;
- (void)setLon:(NSString *)lon;
@property (readonly) BOOL authIsSet;
- (NSString *)getAuth;
- (void)setAuth:(NSString *)auth;
@property (readonly) BOOL tshIsSet;
- (NSInteger)getTsh;
- (void)setTsh:(NSInteger )tsh;
@property (readonly) BOOL tslIsSet;
- (NSInteger)getTsl;
- (void)setTsl:(NSInteger )tsl;

+ (AccessRequest *)deserialiseFromString: (NSString *)string;
+ (AccessRequest *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface AccessResponse : NSObject
{
    NSString *code;
    BOOL codeIsSet;
}

@property (readonly) BOOL codeIsSet;
- (NSString *)getCode;
- (void)setCode:(NSString *)code;

+ (AccessResponse *)deserialiseFromString: (NSString *)string;
+ (AccessResponse *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface KeyRequest : NSObject
{
    NSString *requestId;
    BOOL requestIdIsSet;
    NSString *senderId;
    BOOL senderIdIsSet;
    NSString *auth;
    BOOL authIsSet;
    NSInteger day;
    BOOL dayIsSet;
    NSInteger month;
    BOOL monthIsSet;
    NSInteger year;
    BOOL yearIsSet;
    NSString *msgid;
    BOOL msgidIsSet;
}

@property (readonly) BOOL requestIdIsSet;
- (NSString *)getRequestId;
- (void)setRequestId:(NSString *)requestId;
@property (readonly) BOOL senderIdIsSet;
- (NSString *)getSenderId;
- (void)setSenderId:(NSString *)senderId;
@property (readonly) BOOL authIsSet;
- (NSString *)getAuth;
- (void)setAuth:(NSString *)auth;
@property (readonly) BOOL dayIsSet;
- (NSInteger)getDay;
- (void)setDay:(NSInteger )day;
@property (readonly) BOOL monthIsSet;
- (NSInteger)getMonth;
- (void)setMonth:(NSInteger )month;
@property (readonly) BOOL yearIsSet;
- (NSInteger)getYear;
- (void)setYear:(NSInteger )year;
@property (readonly) BOOL msgidIsSet;
- (NSString *)getMsgid;
- (void)setMsgid:(NSString *)msgid;

+ (KeyRequest *)deserialiseFromString: (NSString *)string;
+ (KeyRequest *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface KeyResponse : NSObject
{
    NSString *code;
    BOOL codeIsSet;
    NSString *uname;
    BOOL unameIsSet;
    NSString *key;
    BOOL keyIsSet;
    NSInteger day;
    BOOL dayIsSet;
    NSInteger month;
    BOOL monthIsSet;
    NSInteger year;
    BOOL yearIsSet;
    NSString *msgid;
    BOOL msgidIsSet;
}

@property (readonly) BOOL codeIsSet;
- (NSString *)getCode;
- (void)setCode:(NSString *)code;
@property (readonly) BOOL unameIsSet;
- (NSString *)getUname;
- (void)setUname:(NSString *)uname;
@property (readonly) BOOL keyIsSet;
- (NSString *)getKey;
- (void)setKey:(NSString *)key;
@property (readonly) BOOL dayIsSet;
- (NSInteger)getDay;
- (void)setDay:(NSInteger )day;
@property (readonly) BOOL monthIsSet;
- (NSInteger)getMonth;
- (void)setMonth:(NSInteger )month;
@property (readonly) BOOL yearIsSet;
- (NSInteger)getYear;
- (void)setYear:(NSInteger )year;
@property (readonly) BOOL msgidIsSet;
- (NSString *)getMsgid;
- (void)setMsgid:(NSString *)msgid;

+ (KeyResponse *)deserialiseFromString: (NSString *)string;
+ (KeyResponse *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface Doorman_sendAccessRequest_reqArg : NSObject
{
    AccessRequest *req;
    BOOL reqIsSet;
}

@property (readonly) BOOL reqIsSet;
- (AccessRequest *)getReq;
- (void)setReq:(AccessRequest *)req;

+ (Doorman_sendAccessRequest_reqArg *)deserialiseFromString: (NSString *)string;
+ (Doorman_sendAccessRequest_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface Doorman_sendAccessRequest_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    AccessResponse *result;
    BOOL resultIsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL resultIsSet;
- (AccessResponse *)getResult;
- (void)setResult:(AccessResponse *)result;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (Doorman_sendAccessRequest_rspArg *)deserialiseFromString: (NSString *)string;
+ (Doorman_sendAccessRequest_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface Doorman_sendKeyRequest_reqArg : NSObject
{
    KeyRequest *req;
    BOOL reqIsSet;
}

@property (readonly) BOOL reqIsSet;
- (KeyRequest *)getReq;
- (void)setReq:(KeyRequest *)req;

+ (Doorman_sendKeyRequest_reqArg *)deserialiseFromString: (NSString *)string;
+ (Doorman_sendKeyRequest_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface Doorman_sendKeyRequest_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    KeyResponse *result;
    BOOL resultIsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL resultIsSet;
- (KeyResponse *)getResult;
- (void)setResult:(KeyResponse *)result;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (Doorman_sendKeyRequest_rspArg *)deserialiseFromString: (NSString *)string;
+ (Doorman_sendKeyRequest_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end
//
// sendAccessRequest
//
@protocol DoormanSendAccessRequestResultSender
- (NSString *)getRequestSenderId;
- (void)successWithResult:(AccessResponse *)result;
@end
@protocol DoormanSendAccessRequestResultReceiver
- (void)successWithResult:(AccessResponse *)result;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol DoormanSendAccessRequestRequestReceiver
- (void)sendAccessRequestWithResultSender:(id<DoormanSendAccessRequestResultSender>)resultSender andReq:(AccessRequest *)req;
@end
@interface DoormanSendAccessRequestExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// sendKeyRequest
//
@protocol DoormanSendKeyRequestResultSender
- (NSString *)getRequestSenderId;
- (void)successWithResult:(KeyResponse *)result;
@end
@protocol DoormanSendKeyRequestResultReceiver
- (void)successWithResult:(KeyResponse *)result;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol DoormanSendKeyRequestRequestReceiver
- (void)sendKeyRequestWithResultSender:(id<DoormanSendKeyRequestResultSender>)resultSender andReq:(KeyRequest *)req;
@end
@interface DoormanSendKeyRequestExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

@interface DoormanSvc : NSObject
+ (void)sendSendAccessRequestUsingResultReceiver:(id<DoormanSendAccessRequestResultReceiver>)resultReceiver andDestination:(NSString *)_dst withReq:(AccessRequest *)req;
+ (void)sendSendAccessRequestUsingResultReceiver:(id<DoormanSendAccessRequestResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withReq:(AccessRequest *)req;
+ (void)sendSendAccessRequestUsingResultHandler:(void (^)(AccessResponse *, DoormanSendAccessRequestExceptionBundle *))resultHandler andDestination:(NSString *)_dst withReq:(AccessRequest *)req;
+ (void)sendSendAccessRequestUsingResultHandler:(void (^)(AccessResponse *, DoormanSendAccessRequestExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withReq:(AccessRequest *)req;
+ (void)sendSendAccessRequestUsingResultReceiver:(id<DoormanSendAccessRequestResultReceiver>)resultReceiver orResultHandler:(void (^)(AccessResponse *, DoormanSendAccessRequestExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withReq:(AccessRequest *)req;
+ (void)registerSendAccessRequestRequestReceiver:(id<DoormanSendAccessRequestRequestReceiver>)requestReceiver;
+ (void)registerSendAccessRequestRequestHandler:(void (^)(id<DoormanSendAccessRequestResultSender> resultSender, AccessRequest * req))requestHandler;

+ (void)sendSendKeyRequestUsingResultReceiver:(id<DoormanSendKeyRequestResultReceiver>)resultReceiver andDestination:(NSString *)_dst withReq:(KeyRequest *)req;
+ (void)sendSendKeyRequestUsingResultReceiver:(id<DoormanSendKeyRequestResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withReq:(KeyRequest *)req;
+ (void)sendSendKeyRequestUsingResultHandler:(void (^)(KeyResponse *, DoormanSendKeyRequestExceptionBundle *))resultHandler andDestination:(NSString *)_dst withReq:(KeyRequest *)req;
+ (void)sendSendKeyRequestUsingResultHandler:(void (^)(KeyResponse *, DoormanSendKeyRequestExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withReq:(KeyRequest *)req;
+ (void)sendSendKeyRequestUsingResultReceiver:(id<DoormanSendKeyRequestResultReceiver>)resultReceiver orResultHandler:(void (^)(KeyResponse *, DoormanSendKeyRequestExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withReq:(KeyRequest *)req;
+ (void)registerSendKeyRequestRequestReceiver:(id<DoormanSendKeyRequestRequestReceiver>)requestReceiver;
+ (void)registerSendKeyRequestRequestHandler:(void (^)(id<DoormanSendKeyRequestResultSender> resultSender, KeyRequest * req))requestHandler;

@end
